name: contacts_bloc_adf
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  equatable: ^2.0.5
  dio: ^5.0.2
  bloc_test: ^9.1.1
  test: ^1.23.1
  mocktail: ^0.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  test_api: 0.4.16

flutter:
  uses-material-design: true
