name: Json Rest Server
port: 3031
host: 192.168.10.113
database: database.json

# auth:
#   jwtSecret: cwsMXDtuP447WZQ63nM4dWZ3RppyMl
#   jwtExpire: 3600
#   unauthorizedStatusCode: 403
#   urlSkip:
#     - /users:
#        method: post
#      - /products/{*}:
#        method: get
